name = "Leonardo F."
license = "MIT"
licenselink = "https://github.com/Track3/hermit/blob/master/LICENSE"
description = "I'm a DevOps Engineer at @ZupInnovation"
homepage = "https://github.com/Valeyard1"
tags = ["blog", "minimal", "dark", "responsive"]
features = [
  "single column",
  "featured image",
  "social icons",
  "google analytics",
  "disqus"
]
min_version = 0.43

[author]
  name = "Leonardo F."
  homepage = "https://github.com/Valeyard1"
